pcd2pgm:
  ros__parameters:
    pcd_file: /home/torosamy/develop-work-space/project/pcd2pgm/PCD/scans.pcd
    odom_to_lidar_odom: [0.0, 0.0, 0.0, 0.0, 0.0, -0.1]
    # odom_to_lidar_odom: [-0.16, 0.0, -0.18, -0.523599, 0.0, -1.5707963]
    flag_pass_through: false
    map_resolution: 0.05
    map_topic_name: map
    thre_radius: 0.5
    thre_z_max: 2.0
    thre_z_min: -0.28
    thres_point_count: 10
    publish_map: false
